// <auto-generated />
using System;
using JdCat.Basketball.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JdCat.Basketball.Model.Migrations
{
    [DbContext(typeof(BasketballDbContext))]
    partial class BasketballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.ActivityEnroll", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AbsentQuantity");

                    b.Property<DateTime>("ActivityTime");

                    b.Property<string>("Address");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("JoinQuantity");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int>("PendingQuantity");

                    b.Property<int>("Quantity");

                    b.Property<string>("Remark");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.Property<int>("UserInfoId");

                    b.HasKey("ID");

                    b.HasIndex("UserInfoId");

                    b.ToTable("ActivityEnroll");
                });

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.ActivityParticipant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivityEnrollId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("FaceUrl");

                    b.Property<int>("Gender");

                    b.Property<DateTime>("JoinTime");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("PlayNumber");

                    b.Property<string>("Remark");

                    b.Property<int>("Status");

                    b.Property<int>("UserInfoId");

                    b.HasKey("ID");

                    b.HasIndex("ActivityEnrollId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("ActivityParticipant");
                });

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Application");

                    b.Property<string>("Callsite");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Exception");

                    b.Property<string>("Level");

                    b.Property<string>("Logger");

                    b.Property<string>("Message");

                    b.HasKey("ID");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.UserInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("FaceUrl");

                    b.Property<int>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("NickName");

                    b.Property<string>("OpenId");

                    b.Property<string>("Phone");

                    b.Property<string>("PlayNumber");

                    b.Property<string>("Province");

                    b.HasKey("ID");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "武汉",
                            Country = "中国",
                            CreateTime = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaceUrl = "https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJfMTu7XeEEA2ZmMOxuowJRf4BXGOXXqZtj6ZTCLeU4cTTsFicMUk8BPW2icVIZwQpfowBotjibAHMFg/132",
                            Gender = 1,
                            NickName = "华天晓",
                            Phone = "17354300837",
                            Province = "湖北"
                        });
                });

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.ActivityEnroll", b =>
                {
                    b.HasOne("JdCat.Basketball.Model.Domain.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JdCat.Basketball.Model.Domain.ActivityParticipant", b =>
                {
                    b.HasOne("JdCat.Basketball.Model.Domain.ActivityEnroll", "ActivityEnroll")
                        .WithMany("ActivityParticipants")
                        .HasForeignKey("ActivityEnrollId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JdCat.Basketball.Model.Domain.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
